import { FileText, Database, Code2, BookOpen, Settings, Home, Search, Calendar, CheckSquare, BarChart3, Clock, TrendingUp, PlusCircle, User, ChevronRight, ChevronLeft, Bookmark as BookmarkIcon, Lightbulb, GraduationCap, PanelRight, Download, Check, Copy, Image as ImageIcon, Edit, Trash2, MoreVertical, Upload, Users, Bot, Send, Lock, LogIn, LogOut, Info, Share2, CheckCircle } from "lucide-react";

export const Icons = {
    Home,
    Bot,
    Send,
    Subjects: BookOpen,
    Notes: FileText,
    FileText,
    Questions: CheckSquare,
    Projects: Code2,
    Code2,
    CaseStudies: Database,
    Database, // Data Acquisition Team icon
    Search,
    Calendar,
    Settings,
    Analytics: BarChart3,
    Time: Clock,
    Clock,
    Trend: TrendingUp,
    Plus: PlusCircle,
    PlusCircle,
    Profile: User,
    ChevronRight,
    ChevronLeft,
    Bookmark: BookmarkIcon,
    CheckSquare,
    Lightbulb,
    GraduationCap,
    Layout: PanelRight,
    Download,
    Check,
    CheckCircle,
    Copy,
    Image: ImageIcon,
    Edit,
    Delete: Trash2,
    Trash2,
    MoreVertical,
    Upload,
    Users: Users,
    Share2,
    Lock,
    LogIn,
    LogOut,
    Info,
};
