import { FileText, Database, Code2, BookOpen, Settings, Home, Search, Calendar, CheckSquare, BarChart3, Clock, TrendingUp, PlusCircle, User, ChevronRight, ChevronLeft, ChevronDown, Bookmark as BookmarkIcon, Lightbulb, GraduationCap, PanelRight, Download, Check, Copy, Image as ImageIcon, Edit, Trash2, MoreVertical, Upload, Users, Bot, Send, Lock, LogIn, LogOut, Info, Share2, CheckCircle, Sparkles, Wand2, Loader2, X, Printer, AlertTriangle, ArrowLeft, Plus, Link2, Globe, RefreshCw, Briefcase, Heart, Music } from "lucide-react";

export const Icons = {
    Printer,
    Home,
    Bot,
    Send,
    Subjects: BookOpen,
    Notes: FileText,
    FileText,
    Questions: CheckSquare,
    Projects: Code2,
    Code2,
    CaseStudies: Database,
    Database, // Data Acquisition Team icon
    Search,
    Calendar,
    Settings,
    Analytics: BarChart3,
    Time: Clock,
    Clock,
    Trend: TrendingUp,
    Plus,
    PlusCircle,
    Profile: User,
    User,
    ChevronRight,
    ChevronLeft,
    ChevronDown,
    Bookmark: BookmarkIcon,
    CheckSquare,
    Lightbulb,
    GraduationCap,
    Layout: PanelRight,
    Download,
    Check,
    CheckCircle,
    Copy,
    Image: ImageIcon,
    Edit,
    Delete: Trash2,
    Trash2,
    MoreVertical,
    Upload,
    Users: Users,
    Share2,
    Lock,
    LogIn,
    LogOut,
    Info,
    AlertTriangle,
    Sparkles,
    Wand2,
    Loader2,
    X,
    ArrowLeft,
    Link: Link2,
    Globe,
    RefreshCw,
    Briefcase,
    Heart,
    Music
};
