import { FileText, Database, Code2, BookOpen, Settings, Home, Search, Calendar, CheckSquare, BarChart3, Clock, TrendingUp, PlusCircle, User, ChevronRight, ChevronLeft, Bookmark as BookmarkIcon, Lightbulb, GraduationCap, PanelRight, Download, Check, Copy, Image as ImageIcon, Edit, Trash2, MoreVertical, Upload } from "lucide-react";

export const Icons = {
    Home,
    Subjects: BookOpen,
    Notes: FileText,
    Questions: CheckSquare,
    Projects: Code2,
    CaseStudies: Database,
    Database, // Data Acquisition Team icon
    Search,
    Calendar,
    Settings,
    Analytics: BarChart3,
    Time: Clock,
    Trend: TrendingUp,
    Plus: PlusCircle,
    PlusCircle,
    Profile: User,
    ChevronRight,
    ChevronLeft,
    Bookmark: BookmarkIcon,
    CheckSquare,
    Lightbulb,
    GraduationCap,
    Layout: PanelRight,
    Download,
    Check,
    Copy,
    Image: ImageIcon,
    Edit,
    Delete: Trash2,
    Trash2,
    MoreVertical,
    Upload,
};
