version: '3.3'
services:
  compreface:
    image: exadel/compreface:latest
    container_name: compreface
    ports:
      - "8000:8000"
    environment:
      - PYTHONBUFFERED=1
    volumes:
      - compreface-data:/var/lib/compreface/data
    restart: always

  compreface-admin:
    image: exadel/compreface-admin:latest
    container_name: compreface-admin
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=compreface
      - POSTGRES_URL=postgres://postgres:compreface@compreface-postgres-db:5432/compreface
    ports:
      - "8001:80"
    depends_on:
      - compreface-postgres-db
    restart: always

  compreface-api:
    image: exadel/compreface-api:latest
    container_name: compreface-api
    depends_on:
      - compreface-postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=compreface
      - POSTGRES_URL=postgres://postgres:compreface@compreface-postgres-db:5432/compreface
    restart: always

  compreface-fe:
    image: exadel/compreface-fe:latest
    container_name: compreface-fe
    ports:
      - "8002:80"
    depends_on:
      - compreface-api
    restart: always

  compreface-postgres-db:
    image: postgres:11.5
    container_name: compreface-postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=compreface
      - POSTGRES_DB=compreface
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

volumes:
  compreface-data:
  postgres-data:
