services:
  - type: web
    name: curriculab
    env: node
    region: singapore
    plan: free
    autoDeploy: false # Disabled to save build minutes
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
