-- ==========================================
-- 1. Faculty & Fellows
-- ==========================================
create table if not exists public.faculty_members (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  status text,
  category text not null check (category in ('faculty', 'fellows')),
  email text,
  subject text,
  gender text not null check (gender in ('male', 'female')),
  contact_no text,
  whatsapp_no text
);

alter table public.faculty_members enable row level security;

-- Policies for Faculty
drop policy if exists "Allow public read access" on public.faculty_members;
create policy "Allow public read access" on public.faculty_members for select to anon using (true);

drop policy if exists "Allow public write access" on public.faculty_members;
create policy "Allow public write access" on public.faculty_members for all to anon using (true) with check (true);


-- ==========================================
-- 2. Subjects
-- ==========================================
create table if not exists public.subjects (
  id text primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  code text not null,
  title text not null,
  icon text,
  color text,
  description text,
  progress integer default 0,
  unit_count integer default 0,
  last_studied text,
  syllabus_pdf_url text
);

alter table public.subjects enable row level security;

drop policy if exists "Allow public read access subjects" on public.subjects;
create policy "Allow public read access subjects" on public.subjects for select to anon using (true);

drop policy if exists "Allow public write access subjects" on public.subjects;
create policy "Allow public write access subjects" on public.subjects for all to anon using (true) with check (true);


-- ==========================================
-- 3. Units
-- ==========================================
create table if not exists public.units (
  id text primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  subject_id text references public.subjects(id) on delete cascade,
  title text not null,
  description text,
  "order" integer not null,
  is_completed boolean default false,
  topics text[]
);

-- Safely add topics column if it doesn't exist (migration for existing tables)
do $$
begin
  if not exists (select 1 from information_schema.columns where table_name = 'units' and column_name = 'topics') then
    alter table public.units add column topics text[];
  end if;
end $$;

alter table public.units enable row level security;

drop policy if exists "Allow public read access units" on public.units;
create policy "Allow public read access units" on public.units for select to anon using (true);

drop policy if exists "Allow public write access units" on public.units;
create policy "Allow public write access units" on public.units for all to anon using (true) with check (true);


-- ==========================================
-- 4. Notes
-- ==========================================
create table if not exists public.notes (
  id text primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unit_id text references public.units(id) on delete cascade,
  title text not null,
  content text,
  is_bookmarked boolean default false,
  last_modified text,
  last_read text
);

alter table public.notes enable row level security;

drop policy if exists "Allow public read access notes" on public.notes;
create policy "Allow public read access notes" on public.notes for select to anon using (true);

drop policy if exists "Allow public write access notes" on public.notes;
create policy "Allow public write access notes" on public.notes for all to anon using (true) with check (true);


-- ==========================================
-- 5. Questions
-- ==========================================
create table if not exists public.questions (
  id text primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unit_id text references public.units(id) on delete cascade,
  subject_id text references public.subjects(id) on delete cascade,
  question text not null,
  answer text,
  marks_type integer,
  tags text[],
  is_bookmarked boolean default false,
  difficulty text check (difficulty in ('Easy', 'Medium', 'Hard'))
);

alter table public.questions enable row level security;

drop policy if exists "Allow public read access questions" on public.questions;
create policy "Allow public read access questions" on public.questions for select to anon using (true);

drop policy if exists "Allow public write access questions" on public.questions;
create policy "Allow public write access questions" on public.questions for all to anon using (true) with check (true);


-- ==========================================
-- 6. Assignments
-- ==========================================
create table if not exists public.assignments (
  id text primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  subject_id text references public.subjects(id) on delete cascade,
  title text not null,
  description text,
  due_date text
);

alter table public.assignments enable row level security;

drop policy if exists "Allow public read access assignments" on public.assignments;
create policy "Allow public read access assignments" on public.assignments for select to anon using (true);

drop policy if exists "Allow public write access assignments" on public.assignments;
create policy "Allow public write access assignments" on public.assignments for all to anon using (true) with check (true);


-- ==========================================
-- 7. Timetable
-- ==========================================
create table if not exists public.timetable (
  id text primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  day text not null,
  subject_title text,
  subject_code text,
  location text,
  start_time text,
  end_time text,
  teacher text,
  progress integer default 0
);

alter table public.timetable enable row level security;

drop policy if exists "Allow public read access timetable" on public.timetable;
create policy "Allow public read access timetable" on public.timetable for select to anon using (true);

drop policy if exists "Allow public write access timetable" on public.timetable;
create policy "Allow public write access timetable" on public.timetable for all to anon using (true) with check (true);


-- ==========================================
-- 8. Announcements
-- ==========================================
create table if not exists public.announcements (
  id text primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  content text,
  date text,
  type text check (type in ('info', 'warning', 'success'))
);

alter table public.announcements enable row level security;

drop policy if exists "Allow public read access announcements" on public.announcements;
create policy "Allow public read access announcements" on public.announcements for select to anon using (true);

drop policy if exists "Allow public write access announcements" on public.announcements;
create policy "Allow public write access announcements" on public.announcements for all to anon using (true) with check (true);


-- ==========================================
-- 9. Teams
-- ==========================================
create table if not exists public.teams (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  lead text,
  color text,
  icon text,
  "order" integer default 0
);

alter table public.teams enable row level security;

drop policy if exists "Allow public read access teams" on public.teams;
create policy "Allow public read access teams" on public.teams for select to anon using (true);

drop policy if exists "Allow public write access teams" on public.teams;
create policy "Allow public write access teams" on public.teams for all to anon using (true) with check (true);


-- ==========================================
-- 10. Team Members
-- ==========================================
-- TEAM MEMBERS
create table if not exists public.team_members (
  id uuid not null default gen_random_uuid (),
  team_id bigint not null references public.teams (id) on delete cascade,
  name text not null,
  role text not null,
  subject text,
  drive_link text,
  created_at timestamp with time zone not null default now(),
  constraint team_members_pkey primary key (id)
);
alter table public.team_members enable row level security;

drop policy if exists "Enable read access for all users" on public.team_members;
create policy "Enable read access for all users" on public.team_members for select using (true);

drop policy if exists "Enable write access for authenticated users only" on public.team_members;
create policy "Enable write access for authenticated users only" on public.team_members for all to authenticated using (true) with check (true);


-- ==========================================
-- 11. Workflow Steps
-- ==========================================
-- WORKFLOW STEPS
create table if not exists public.workflow_steps (
  id uuid not null default gen_random_uuid (),
  title text not null,
  description text not null,
  icon text not null,
  "order" integer not null,
  created_at timestamp with time zone not null default now(),
  constraint workflow_steps_pkey primary key (id)
);
alter table public.workflow_steps enable row level security;

drop policy if exists "Enable read access for all users" on public.workflow_steps;
create policy "Enable read access for all users" on public.workflow_steps for select using (true);

drop policy if exists "Enable write access for authenticated users only" on public.workflow_steps;
create policy "Enable write access for authenticated users only" on public.workflow_steps for all to authenticated using (true) with check (true);


-- CHANGELOGS
create table if not exists public.change_logs (
  id uuid not null default gen_random_uuid (),
  entity_type text not null,
  entity_id text not null,
  action text not null,
  changed_by text not null,
  changes jsonb,
  timestamp timestamp with time zone not null default now(),
  constraint change_logs_pkey primary key (id)
);
alter table public.change_logs enable row level security;

drop policy if exists "Enable read access for all users" on public.change_logs;
create policy "Enable read access for all users" on public.change_logs for select using (true);

drop policy if exists "Enable insert for authenticated users only" on public.change_logs;
create policy "Enable insert for authenticated users only" on public.change_logs for insert to authenticated with check (true);
