-- Create the table for Faculty and Fellows
create table public.faculty_members (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  status text,
  category text not null check (category in ('faculty', 'fellows')),
  email text,
  subject text,
  gender text not null check (gender in ('male', 'female')),
  contact_no text,
  whatsapp_no text
);

-- Enable Row Level Security (RLS)
alter table public.faculty_members enable row level security;

-- Create Policy: Allow public read access
create policy "Allow public read access"
on public.faculty_members for select
to anon
using (true);

-- Create Policy: Allow public write access (insert, update, delete)
-- CAUTION: This allows anyone with the API key to modify data. 
-- In a real production app with auth, you would restrict this to authenticated admins.
create policy "Allow public write access"
on public.faculty_members for all
to anon
using (true)
with check (true);
