"use client"

import React, { useState, useEffect, useRef } from 'react';
import { Icons } from '@/components/shared/Icons';
import { cn } from '@/lib/utils';
import { Note, Subject } from '@/types';

interface NoteExplorerProps {
    note: Note;
    subject?: Subject;
    onBack: () => void;
}

export function NoteExplorer({ note, subject, onBack }: NoteExplorerProps) {
    const [scrolled, setScrolled] = useState(false);
    const [copied, setCopied] = useState(false);
    const contentRef = useRef<HTMLDivElement>(null);

    useEffect(() => {
        const handleScroll = () => {
            setScrolled(window.scrollY > 100);
        };
        window.addEventListener('scroll', handleScroll);
        return () => window.removeEventListener('scroll', handleScroll);
    }, []);


    const handleCopyMarkdown = () => {
        const markdown = `# ${note.title}

> **Subject:** ${subject?.code || ''} - ${subject?.title || ''}
> **Category:** Academic Notes
> **Last Modified:** ${note.lastModified}
> **Source:** CurricuLab Personal Archive

---

## Introduction
${note.content}
This section outlines the primary objectives and foundational theories behind ${note.title}. In the context of the MBA Business Analytics curriculum, understanding these prerequisites is critical for advanced application.

![Illustrative Diagram](https://images.unsplash.com/photo-1551288049-bbda38a5f85d?auto=format&fit=crop&q=80&w=1200)
*Figure 1: Conceptual Framework for Operational Analytics*

## Core Concepts

### Efficiency Scaling
Understanding how operational throughput improves with optimized resource allocation.

### Process Mapping
Visualizing the end-to-end journey of data and physical resources in production.

---

## Performance Comparison
| Metric | Traditional Method | CurricuLab Analytics | Improvement |
| :--- | :--- | :--- | :--- |
| Data Processing | 45 min | 12 min | 73% Speedup |
| Error Rate | 4.2% | 0.8% | 81% Reduction |
| Cost-per-Analysis | $12.50 | $3.20 | 74% Savings |

---

## Methodology
Our approach to analyzing ${note.title} involves a systematic breakdown of historical data points, followed by predictive modeling. This dual-phase methodology ensures both theoretical accuracy and practical relevance.

> "The synthesis of quantitative data with qualitative insights remains the gold standard for business intelligence in the current digital landscape."

---

## Summary & Key Takeaways
- Data-driven decision making is non-negotiable.
- Seamless process integration reduces overhead by up to 30%.
- Visual storytelling bridges the gap between analysts and executives.

---
*Generated by CurricuLab on ${new Date().toLocaleDateString()}*`;

        navigator.clipboard.writeText(markdown);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };


    return (
        <div className="min-h-screen bg-[#fafbfc] pb-20">
            {/* Header / TOC Bar */}
            <div className={cn(
                "sticky top-0 z-40 bg-white/80 backdrop-blur-md border-b border-gray-100 transition-all duration-300",
                scrolled ? "py-2 shadow-sm" : "py-4"
            )}>
                <div className="max-w-5xl mx-auto px-6 flex items-center justify-between gap-8">
                    <button
                        onClick={onBack}
                        className="p-2.5 hover:bg-gray-50 rounded-[18px] transition-all text-gray-400 hover:text-gray-900 group"
                    >
                        <Icons.ChevronLeft size={22} className="group-hover:-translate-x-1 transition-transform" />
                    </button>

                    <div className="flex-1 flex items-center gap-3 min-w-0">
                        <div className="flex items-center gap-2 shrink-0">
                            <span className="text-[10px] font-black text-blue-600 uppercase tracking-[0.2em]">
                                {subject?.code || 'NOTE'}
                            </span>
                            <span className="text-gray-200 font-extralight text-sm">/</span>
                        </div>
                        <h1 className="text-sm font-black text-gray-900 truncate tracking-tight">
                            {note.title}
                        </h1>
                    </div>

                    <div className="flex items-center gap-4 shrink-0">
                        <button
                            onClick={handleCopyMarkdown}
                            className={cn(
                                "flex items-center gap-3 px-6 py-2.5 rounded-[18px] text-[10px] font-black uppercase tracking-widest transition-all shadow-sm",
                                copied
                                    ? "bg-green-600 text-white shadow-lg shadow-green-100 scale-95"
                                    : "bg-blue-600 text-white hover:bg-blue-700 shadow-lg shadow-blue-100"
                            )}
                        >
                            {copied ? <Icons.Check size={16} /> : <Icons.Copy size={16} />}
                            {copied ? 'Copied to Clipboard' : 'Export Markdown'}
                        </button>
                    </div>
                </div>
            </div>

            {/* Note Content */}
            <main className="max-w-4xl mx-auto px-6 py-12">
                <div className="bg-white border border-gray-100 rounded-[50px] p-12 md:p-20 shadow-sm relative overflow-hidden">
                    {/* Decorative Background Element */}
                    <div className="absolute top-0 right-0 w-64 h-64 bg-gradient-to-br from-blue-500/5 to-transparent rounded-bl-full pointer-events-none" />

                    <div className="relative space-y-12">
                        {/* Title Section (Hidden on Print because of the print-only header) */}
                        <div className="space-y-4">
                            <div className="flex items-center gap-3">
                                <div className="w-12 h-12 bg-blue-600 rounded-2xl flex items-center justify-center text-white shadow-lg shadow-blue-200">
                                    <Icons.Notes size={24} />
                                </div>
                                <div>
                                    <h2 className="text-3xl font-black text-gray-900 tracking-tight">
                                        {note.title}
                                    </h2>
                                    <p className="text-sm font-bold text-gray-400 uppercase tracking-widest">
                                        Last Edited {note.lastModified}
                                    </p>
                                </div>
                            </div>
                        </div>

                        {/* Content Body */}
                        <div className="prose prose-blue max-w-none" ref={contentRef}>
                            <section className="space-y-6">
                                <h3 className="text-2xl font-black text-gray-900 tracking-tight">Introduction</h3>
                                <p className="text-lg text-gray-600 leading-relaxed font-medium whitespace-pre-wrap">
                                    {note.content}
                                    <span>
                                        {" "}This section outlines the primary objectives and foundational theories behind {note.title}. In the context of the MBA Business Analytics curriculum, understanding these prerequisites is critical for advanced application.
                                    </span>
                                </p>

                                {/* Illustrative Diagram Placeholder */}
                                <div className="mt-8 space-y-3">
                                    <div className="aspect-video bg-gray-50 rounded-[40px] border-2 border-dashed border-gray-200 flex flex-col items-center justify-center text-gray-400 group cursor-pointer hover:border-blue-300 hover:bg-blue-50/30 transition-all">
                                        <div className="w-16 h-16 rounded-full bg-white flex items-center justify-center shadow-sm group-hover:scale-110 group-hover:text-blue-600 transition-all">
                                            <Icons.Image size={32} />
                                        </div>
                                        <p className="mt-4 font-black uppercase tracking-widest text-[10px]">Reference Diagram: Analytic Framework</p>
                                    </div>
                                    <p className="text-center italic text-xs text-gray-400 font-bold">Figure 1: Conceptual Framework for Operational Analytics</p>
                                </div>
                            </section>

                            <section className="space-y-8 mt-16">
                                <h3 className="text-2xl font-black text-gray-900 tracking-tight">Core Concepts</h3>
                                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                                    <div className="p-8 bg-blue-50 rounded-[30px] border border-blue-100 space-y-3">
                                        <div className="w-10 h-10 bg-white rounded-xl flex items-center justify-center text-blue-600 shadow-sm">
                                            <Icons.Trend size={20} />
                                        </div>
                                        <h4 className="font-black text-gray-900">Efficiency Scaling</h4>
                                        <p className="text-sm text-gray-500 font-bold">Understanding how operational throughput improves with optimized resource allocation.</p>
                                    </div>
                                    <div className="p-8 bg-orange-50 rounded-[30px] border border-orange-100 space-y-3">
                                        <div className="w-10 h-10 bg-white rounded-xl flex items-center justify-center text-orange-600 shadow-sm">
                                            <Icons.Layout size={20} />
                                        </div>
                                        <h4 className="font-black text-gray-900">Process Mapping</h4>
                                        <p className="text-sm text-gray-500 font-bold">Visualizing the end-to-end journey of data and physical resources in production.</p>
                                    </div>
                                </div>
                            </section>

                            <section className="space-y-8 mt-16">
                                <h3 className="text-2xl font-black text-gray-900 tracking-tight">Performance Analysis</h3>
                                <div className="overflow-hidden bg-white border border-gray-100 rounded-[30px] shadow-sm">
                                    <table className="w-full text-left border-collapse">
                                        <thead>
                                            <tr className="bg-gray-50/80 border-b border-gray-100">
                                                <th className="px-8 py-5 text-[10px] font-black uppercase tracking-widest text-gray-500">Metric</th>
                                                <th className="px-8 py-5 text-[10px] font-black uppercase tracking-widest text-gray-500">Traditional</th>
                                                <th className="px-8 py-5 text-[10px] font-black uppercase tracking-widest text-blue-600">CurricuLab</th>
                                                <th className="px-8 py-5 text-[10px] font-black uppercase tracking-widest text-green-600 text-right">Gain</th>
                                            </tr>
                                        </thead>
                                        <tbody className="divide-y divide-gray-50">
                                            {[
                                                { m: "Data Processing", t: "45 min", c: "12 min", g: "73% Speedup" },
                                                { m: "Error Rate", t: "4.2%", c: "0.8%", g: "81% Reduction" },
                                                { m: "Cost-per-Analysis", t: "$12.50", c: "$3.20", g: "74% Savings" },
                                            ].map((row, i) => (
                                                <tr key={i} className="hover:bg-blue-50/30 transition-colors group">
                                                    <td className="px-8 py-6 font-bold text-gray-900">{row.m}</td>
                                                    <td className="px-8 py-6 text-gray-500 font-medium">{row.t}</td>
                                                    <td className="px-8 py-6 text-blue-600 font-black">{row.c}</td>
                                                    <td className="px-8 py-6 text-green-600 font-black text-right">{row.g}</td>
                                                </tr>
                                            ))}
                                        </tbody>
                                    </table>
                                </div>
                            </section>

                            <section className="space-y-6 mt-16">
                                <h3 className="text-2xl font-black text-gray-900 tracking-tight">Methodology</h3>
                                <p className="text-lg text-gray-600 leading-relaxed font-medium">
                                    Our approach to analyzing {note.title} involves a systematic breakdown of historical data points, followed by predictive modeling. This dual-phase methodology ensures both theoretical accuracy and practical relevance.
                                </p>
                                <div className="bg-gray-50 p-8 rounded-[30px] border border-gray-100 italic text-gray-500 font-medium">
                                    "The synthesis of quantitative data with qualitative insights remains the gold standard for business intelligence in the current digital landscape."
                                </div>
                            </section>

                            <section className="space-y-6 mt-16 pt-16 border-t border-gray-100">
                                <h3 className="text-2xl font-black text-gray-900 tracking-tight">Summary & Key Takeaways</h3>
                                <ul className="space-y-4">
                                    {[
                                        "Data-driven decision making is non-negotiable.",
                                        "Seamless process integration reduces overhead by up to 30%.",
                                        "Visual storytelling bridges the gap between analysts and executives."
                                    ].map((point, i) => (
                                        <li key={i} className="flex gap-4 items-start">
                                            <div className="w-6 h-6 bg-green-100 rounded-full flex items-center justify-center text-green-600 shrink-0 mt-1">
                                                <Icons.Check size={14} />
                                            </div>
                                            <span className="text-lg text-gray-600 font-medium">{point}</span>
                                        </li>
                                    ))}
                                </ul>
                            </section>
                        </div>

                        {/* Footer Controls */}
                        <div className="flex items-center justify-between pt-12 border-t border-gray-100 mt-12">
                            <button className="flex items-center gap-3 px-8 py-4 bg-gray-50 hover:bg-gray-100 rounded-[24px] text-gray-600 font-black tracking-tight uppercase text-xs transition-all">
                                <Icons.ChevronLeft size={18} />
                                Previous Note
                            </button>
                            <button className="flex items-center gap-3 px-8 py-4 bg-blue-600 hover:bg-blue-700 text-white rounded-[24px] font-black tracking-tight uppercase text-xs transition-all shadow-lg shadow-blue-100">
                                Next Note
                                <Icons.ChevronRight size={18} />
                            </button>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    );
}
