-- ================================================================
-- CurricuLab Database Complete Setup Script
-- ================================================================
-- Run this ONCE in your Supabase SQL Editor to set up all tables
-- This script is idempotent (safe to run multiple times)
-- ================================================================

-- ==========================================
-- 1. Faculty & Fellows
-- ==========================================
CREATE TABLE IF NOT EXISTS public.faculty_members (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  name text NOT NULL,
  status text,
  category text NOT NULL CHECK (category IN ('faculty', 'fellows')),
  email text,
  subject text,
  gender text NOT NULL CHECK (gender IN ('male', 'female')),
  contact_no text,
  whatsapp_no text
);

ALTER TABLE public.faculty_members ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read access" ON public.faculty_members;
CREATE POLICY "Allow public read access" ON public.faculty_members FOR SELECT TO anon USING (true);

DROP POLICY IF EXISTS "Allow public write access" ON public.faculty_members;
CREATE POLICY "Allow public write access" ON public.faculty_members FOR ALL TO anon USING (true) WITH CHECK (true);


-- ==========================================
-- 2. Subjects Table
-- ==========================================
CREATE TABLE IF NOT EXISTS public.subjects (
  id text PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  code text NOT NULL UNIQUE,
  title text NOT NULL,
  icon text,
  color text,
  description text,
  progress integer DEFAULT 0,
  unit_count integer DEFAULT 0,
  last_studied text
);

-- Add missing columns if they don't exist (for existing databases)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'subjects' AND column_name = 'progress') THEN
        ALTER TABLE public.subjects ADD COLUMN progress integer DEFAULT 0;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'subjects' AND column_name = 'unit_count') THEN
        ALTER TABLE public.subjects ADD COLUMN unit_count integer DEFAULT 0;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'subjects' AND column_name = 'last_studied') THEN
        ALTER TABLE public.subjects ADD COLUMN last_studied text;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'subjects' AND column_name = 'icon') THEN
        ALTER TABLE public.subjects ADD COLUMN icon text;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'subjects' AND column_name = 'color') THEN
        ALTER TABLE public.subjects ADD COLUMN color text;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'subjects' AND column_name = 'description') THEN
        ALTER TABLE public.subjects ADD COLUMN description text;
    END IF;
END $$;

ALTER TABLE public.subjects ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read access subjects" ON public.subjects;
CREATE POLICY "Allow public read access subjects" ON public.subjects FOR SELECT TO anon USING (true);

DROP POLICY IF EXISTS "Allow public write access subjects" ON public.subjects;
CREATE POLICY "Allow public write access subjects" ON public.subjects FOR ALL TO anon USING (true) WITH CHECK (true);


-- ==========================================
-- 3. Units Table
-- ==========================================
CREATE TABLE IF NOT EXISTS public.units (
  id text PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  subject_id text REFERENCES public.subjects(id) ON DELETE CASCADE,
  unit_code text,
  title text NOT NULL,
  description text,
  "order" integer NOT NULL,
  is_completed boolean DEFAULT false,
  topics text[]
);

-- Add missing columns if they don't exist (for existing databases)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'units' AND column_name = 'topics') THEN
        ALTER TABLE public.units ADD COLUMN topics text[];
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'units' AND column_name = 'description') THEN
        ALTER TABLE public.units ADD COLUMN description text;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'units' AND column_name = 'order') THEN
        ALTER TABLE public.units ADD COLUMN "order" integer DEFAULT 0;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'units' AND column_name = 'is_completed') THEN
        ALTER TABLE public.units ADD COLUMN is_completed boolean DEFAULT false;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'units' AND column_name = 'unit_code') THEN
        ALTER TABLE public.units ADD COLUMN unit_code text;
    END IF;
END $$;

ALTER TABLE public.units ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read access units" ON public.units;
CREATE POLICY "Allow public read access units" ON public.units FOR SELECT TO anon USING (true);

DROP POLICY IF EXISTS "Allow public write access units" ON public.units;
CREATE POLICY "Allow public write access units" ON public.units FOR ALL TO anon USING (true) WITH CHECK (true);


-- ==========================================
-- 4. Notes Table
-- ==========================================
CREATE TABLE IF NOT EXISTS public.notes (
  id text PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  unit_id text REFERENCES public.units(id) ON DELETE CASCADE,
  title text NOT NULL,
  content text,
  is_bookmarked boolean DEFAULT false,
  last_modified text,
  last_read text
);

ALTER TABLE public.notes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read access notes" ON public.notes;
CREATE POLICY "Allow public read access notes" ON public.notes FOR SELECT TO anon USING (true);

DROP POLICY IF EXISTS "Allow public write access notes" ON public.notes;
CREATE POLICY "Allow public write access notes" ON public.notes FOR ALL TO anon USING (true) WITH CHECK (true);


-- ==========================================
-- 5. Enable Realtime for Subjects
-- ==========================================
-- This allows Supabase Realtime to broadcast changes
DROP PUBLICATION IF EXISTS supabase_realtime_subjects;
CREATE PUBLICATION supabase_realtime_subjects FOR TABLE public.subjects;


-- ==========================================
-- 6. Create Indexes for Performance
-- ==========================================
CREATE INDEX IF NOT EXISTS idx_units_subject_id ON public.units(subject_id);
CREATE INDEX IF NOT EXISTS idx_notes_unit_id ON public.notes(unit_id);
CREATE INDEX IF NOT EXISTS idx_subjects_code ON public.subjects(code);


-- ==========================================
-- Success Message
-- ==========================================
DO $$
BEGIN
    RAISE NOTICE '✅ Database setup completed successfully!';
    RAISE NOTICE '📊 Tables created: faculty_members, subjects, units, notes';
    RAISE NOTICE '🔒 RLS policies enabled for all tables';
    RAISE NOTICE '⚡ Realtime enabled for subjects';
    RAISE NOTICE '🚀 Ready to use!';
END $$;
