-- Seed Missing Resources Data
-- Migrating from:
-- lib/data/syllabus-links.ts
-- lib/data/article-links.ts
-- lib/data/interview-resources.ts
-- lib/data/gpt-resources.ts

INSERT INTO public.resources (id, title, description, type, url, category, topic, content) VALUES
-- From SYLLABUS_RESOURCES (syllabus-links.ts)
('syl-pb204-1', 'Nature & Scope of Operations Mgmt', 'YouTube Search: Nature, scope, importance and functions', 'Link', 'https://www.youtube.com/results?search_query=Production+and+Operation+Management+Nature%2C+scope%2C+importance+and+functions+of+Operations+Management', 'Academic', 'Operations Mgmt', NULL),
('syl-pb204-2', 'Evolution of Factory System', 'YouTube Search: History of manufacturing', 'Link', 'https://www.youtube.com/results?search_query=Production+and+Operation+Management+Evolution+of+the+factory+system', 'Academic', 'Operations Mgmt', NULL),
('syl-pb204-3', 'Quality Management (Deming, Crosby)', 'YouTube Search: Contributions of Quality Gurus', 'Link', 'https://www.youtube.com/results?search_query=Production+and+Operation+Management+Contributions%3A+Henry+Ford%2C+Deming%2C+Crosby%2C+Taguchi', 'Academic', 'Operations Mgmt', NULL),
('syl-pb204-4', 'Work Study & Productivity', 'YouTube Search: Objectives and scope of Work Study', 'Link', 'https://www.youtube.com/results?search_query=Production+and+Operation+Management+Work+Study%3A+objectives%2C+scope+and+uses', 'Academic', 'Operations Mgmt', NULL),
('syl-pb204-5', 'Facilities Location & Layout', 'YouTube Search: Strategic importance of location', 'Link', 'https://www.youtube.com/results?search_query=Production+and+Operation+Management+Strategic+importance+of+facilities+location+and+layout', 'Academic', 'Operations Mgmt', NULL),
('syl-pb204-6', 'Types of Manufacturing Systems', 'YouTube Search: Jobbing, Batch, Flow production', 'Link', 'https://www.youtube.com/results?search_query=Production+and+Operation+Management+Methods+of+manufacturing', 'Academic', 'Operations Mgmt', NULL),
('syl-pb204-7', 'Statistical Quality Control (SQC)', 'YouTube Search: SQC and Control Charts', 'Link', 'https://www.youtube.com/results?search_query=Production+and+Operation+Management+Statistical+Quality+Control+%28SQC%29', 'Academic', 'Operations Mgmt', NULL),
('syl-pb204-8', 'Six Sigma Introduction', 'YouTube Search: Basics of Six Sigma', 'Link', 'https://www.youtube.com/results?search_query=Production+and+Operation+Management+Introduction+to+Six+Sigma', 'Academic', 'Operations Mgmt', NULL),
('syl-pb204-9', 'Toyota Production System (JIT)', 'YouTube Search: Lean production and JIT', 'Link', 'https://www.youtube.com/results?search_query=Production+and+Operation+Management+Toyota+production+system', 'Academic', 'Operations Mgmt', NULL),

('syl-pb205-1', 'What is Digital Transformation?', 'YouTube Search: Definition and Scope', 'Link', 'https://www.youtube.com/results?search_query=Digital+Transformation+Definition+of+digital+transformation', 'Academic', 'Digital Transformation', NULL),
('syl-pb205-2', 'Key Drivers of Transformation', 'YouTube Search: Drivers and Trends', 'Link', 'https://www.youtube.com/results?search_query=Digital+Transformation+Key+drivers+of+digital+transformation', 'Academic', 'Digital Transformation', NULL),
('syl-pb205-3', 'Agile & Lean in Digital', 'YouTube Search: Applying Agile principles', 'Link', 'https://www.youtube.com/results?search_query=Digital+Transformation+Applying+Agile+principles+to+digital+transformation', 'Academic', 'Digital Transformation', NULL),
('syl-pb205-4', 'FinTech Innovations', 'YouTube Search: Trends in Financial Tech', 'Link', 'https://www.youtube.com/results?search_query=Digital+Transformation+FinTech+innovations+and+trends', 'Academic', 'Digital Transformation', NULL),
('syl-pb205-5', 'Digital Health & Telemedicine', 'YouTube Search: Tech transforming healthcare', 'Link', 'https://www.youtube.com/results?search_query=Digital+Transformation+Technologies+transforming+healthcare+%28telemedicine%29', 'Academic', 'Digital Transformation', NULL),
('syl-pb205-6', 'Disruptive Innovation', 'YouTube Search: Types of innovation', 'Link', 'https://www.youtube.com/results?search_query=Digital+Transformation+Types+of+innovation%3A+disruptive', 'Academic', 'Digital Transformation', NULL),
('syl-pb205-7', 'Design Thinking', 'YouTube Search: Design thinking process', 'Link', 'https://www.youtube.com/results?search_query=Digital+Transformation+Design+thinking', 'Academic', 'Digital Transformation', NULL),
('syl-pb205-8', 'Artificial Intelligence (AI)', 'YouTube Search: AI in Digital Transformation', 'Link', 'https://www.youtube.com/results?search_query=Digital+Transformation+Artificial+Intelligence+%28AI%29', 'Academic', 'Digital Transformation', NULL),
('syl-pb205-9', 'Blockchain Technology', 'YouTube Search: Blockchain basics', 'Link', 'https://www.youtube.com/results?search_query=Digital+Transformation+Blockchain', 'Academic', 'Digital Transformation', NULL),

('syl-pb206-1', 'Valid Contract Elements', 'YouTube Search: Essentials of a contract', 'Link', 'https://www.youtube.com/results?search_query=Legal+Aspects+of+Business+Essential+elements+of+a+valid+contract', 'Academic', 'Business Law', NULL),
('syl-pb206-2', 'Offer and Acceptance', 'YouTube Search: Rules of offer/acceptance', 'Link', 'https://www.youtube.com/results?search_query=Legal+Aspects+of+Business+Offer+and+acceptance', 'Academic', 'Business Law', NULL),
('syl-pb206-3', 'Breach of Contract Remedies', 'YouTube Search: Legal remedies for breach', 'Link', 'https://www.youtube.com/results?search_query=Legal+Aspects+of+Business+Remedies+for+breach+of+contract', 'Academic', 'Business Law', NULL),
('syl-pb206-4', 'Sales of Goods Act 1930', 'YouTube Search: General principles', 'Link', 'https://www.youtube.com/results?search_query=Legal+Aspects+of+Business+Sales+of+Goods+Act%2C+1930%3A+general+principles', 'Academic', 'Business Law', NULL),
('syl-pb206-5', 'Condition vs Warranty', 'YouTube Search: Legal distinction', 'Link', 'https://www.youtube.com/results?search_query=Legal+Aspects+of+Business+Conditions+and+warranties', 'Academic', 'Business Law', NULL),
('syl-pb206-6', 'Partnership Act 1932', 'YouTube Search: Rights and liabilities', 'Link', 'https://www.youtube.com/results?search_query=Legal+Aspects+of+Business+Indian+Partnership+Act%2C+1932%3A+definition+and+general+principles', 'Academic', 'Business Law', NULL),
('syl-pb206-7', 'Company Law: Formation', 'YouTube Search: Formation of a company', 'Link', 'https://www.youtube.com/results?search_query=Legal+Aspects+of+Business+Formation+of+a+company', 'Academic', 'Business Law', NULL),
('syl-pb206-8', 'Memorandum of Association (MOA)', 'YouTube Search: MOA and AOA', 'Link', 'https://www.youtube.com/results?search_query=Legal+Aspects+of+Business+Memorandum+of+association', 'Academic', 'Business Law', NULL),
('syl-pb206-9', 'Directors & Meetings', 'YouTube Search: Company directors rules', 'Link', 'https://www.youtube.com/results?search_query=Legal+Aspects+of+Business+Directors', 'Academic', 'Business Law', NULL),

('syl-pb207-1', 'Intro to Data Visualization', 'YouTube Search: Why and how to visualize', 'Link', 'https://www.youtube.com/results?search_query=Data+Visualization+and+Story+Telling+Introduction+to+visualization', 'Academic', 'Data Visualization', NULL),
('syl-pb207-2', 'Visual Analysis Stages', 'YouTube Search: Stages of data visualizing', 'Link', 'https://www.youtube.com/results?search_query=Data+Visualization+and+Story+Telling+Stages+of+data+visualizing', 'Academic', 'Data Visualization', NULL),
('syl-pb207-3', 'Exploratory & Univariate Analysis', 'YouTube Search: Structured data visualization', 'Link', 'https://www.youtube.com/results?search_query=Data+Visualization+and+Story+Telling+Exploratory+analysis', 'Academic', 'Data Visualization', NULL),
('syl-pb207-4', 'Visualizing Text Data', 'YouTube Search: Word clouds and text mining', 'Link', 'https://www.youtube.com/results?search_query=Data+Visualization+and+Story+Telling+Visualizing+text+data', 'Academic', 'Data Visualization', NULL),
('syl-pb207-5', 'Storytelling with Data', 'YouTube Search: Narrative framework', 'Link', 'https://www.youtube.com/results?search_query=Data+Visualization+and+Story+Telling+Introduction+to+visual+storytelling', 'Academic', 'Data Visualization', NULL),
('syl-pb207-6', 'Science of Storytelling', 'YouTube Search: Cognitive science of stories', 'Link', 'https://www.youtube.com/results?search_query=Data+Visualization+and+Story+Telling+Science+behind+storytelling', 'Academic', 'Data Visualization', NULL),
('syl-pb207-7', 'Dashboard Design Principles', 'YouTube Search: Effective dashboards', 'Link', 'https://www.youtube.com/results?search_query=Data+Visualization+and+Story+Telling+Analytics+dashboards', 'Academic', 'Data Visualization', NULL),

('syl-pb208-1', 'Research Design & Types', 'YouTube Search: Exploratory vs Descriptive', 'Link', 'https://www.youtube.com/results?search_query=Business+Research+Methodology+Research+design%3A+definitions+and+functions', 'Academic', 'Business Research', NULL),
('syl-pb208-2', 'Sampling Design', 'YouTube Search: Probability methods', 'Link', 'https://www.youtube.com/results?search_query=Business+Research+Methodology+Sampling+design', 'Academic', 'Business Research', NULL),
('syl-pb208-3', 'Questionnaire Design', 'YouTube Search: Scales and questions', 'Link', 'https://www.youtube.com/results?search_query=Business+Research+Methodology+Questionnaire+designing', 'Academic', 'Business Research', NULL),
('syl-pb208-4', 'Hypothesis Testing', 'YouTube Search: Concept and steps', 'Link', 'https://www.youtube.com/results?search_query=Business+Research+Methodology+Hypothesis+testing%3A+concept', 'Academic', 'Business Research', NULL),
('syl-pb208-5', 'ANOVA & Chi-Square', 'YouTube Search: Statistical tests', 'Link', 'https://www.youtube.com/results?search_query=Business+Research+Methodology+ANOVA', 'Academic', 'Business Research', NULL),
('syl-pb208-6', 'Factor & Conjoint Analysis', 'YouTube Search: Advanced techniques', 'Link', 'https://www.youtube.com/results?search_query=Business+Research+Methodology+Basic+concepts+of+factor+analysis', 'Academic', 'Business Research', NULL),

-- From ARTICLE_RESOURCES (article-links.ts)
('art-ba-1', '4 Types of Data Analytics', 'HBS Online: Descriptive to Prescriptive', 'Article', 'https://online.hbs.edu/blog/post/types-of-data-analysis', 'Academic', 'Analytics Foundations', NULL),
('art-ba-2', 'Analytics Types Overview', 'Univ of Bath: Three types of analytics', 'Article', 'https://online.bath.ac.uk/content/descriptive-predictive-and-prescriptive-three-types-business-analytics', 'Academic', 'Analytics Foundations', NULL),
('art-ba-3', 'Guide to Data Analytics Types', 'Insightsoftware: Comparing analytics types', 'Article', 'https://insightsoftware.com/blog/comparing-descriptive-predictive-prescriptive-and-diagnostic-analytics/', 'Academic', 'Analytics Foundations', NULL),
('art-sql-1', 'SQL Tutorial (W3Schools)', 'W3Schools: Comprehensive SQL basics', 'Article', 'https://www.w3schools.com/sql/', 'Academic', 'SQL', NULL),
('art-sql-2', 'SQL for Data Analysis Intro', 'ThoughtSpot: Tutorial introduction', 'Article', 'https://www.thoughtspot.com/sql-tutorial/introduction-to-sql', 'Academic', 'SQL', NULL),
('art-sql-3', 'SQL Beginner Tutorial', 'Data36: Hands-on SQL guide', 'Article', 'https://data36.com/sql-for-data-analysis-tutorial-beginners/', 'Academic', 'SQL', NULL),
('art-stat-1', 'Statistical Analysis Guidelines', 'PubMed: Choosing appropriate tests', 'Article', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC11467495/', 'Academic', 'Statistics', NULL),
('art-stat-2', 'Understanding Regression', 'SAGE: Hypothesis testing in regression', 'Article', 'https://methods.sagepub.com/book/mono/understanding-regression-analysis/chpt/hypothesis-testing', 'Academic', 'Statistics', NULL),
('art-viz-1', 'Viz Best Practices', 'Tableau: Tips for effective viz', 'Article', 'https://www.tableau.com/visualization/data-visualization-best-practices', 'Academic', 'Data Visualization', NULL),
('art-viz-2', 'How to Tell a Great Story', 'ThoughtSpot: Data storytelling guide', 'Article', 'https://www.thoughtspot.com/data-trends/best-practices/data-storytelling', 'Academic', 'Data Visualization', NULL),
('art-viz-3', 'Storytelling Best Practices', 'Domo: From dashboards to impact', 'Article', 'https://www.domo.com/blog/data-storytelling-best-practices-from-dashboards-to-impact', 'Academic', 'Data Visualization', NULL),
('art-viz-4', 'Data Viz & Storytelling (PDF)', 'IE University: Comprehensive notes', 'PDF', 'https://files.thesaurus.ie.edu/data-visualization-dashboards-storytelling.pdf', 'Academic', 'Data Visualization', NULL),

-- From GPT_RESOURCES (gpt-resources.ts)
('gpt-1', 'Exam Ready Analytics Coach', 'Your personalized AI coach for mastering analytics exams and concepts.', 'Link', 'https://chatgpt.com/g/g-696a4f4a8f708191bc92fa570a0dd7ea-exam-ready-analytics-coach', 'Gems GPTs', 'AI Tools', NULL),
('gpt-2', 'RAG Business Strategist', 'Advanced AI for business strategy utilizing Retrieval-Augmented Generation.', 'Link', 'https://chatgpt.com/g/g-696a452ba3048191b6e11ebf685fe068-rag-business-strategist', 'Gems GPTs', 'AI Tools', NULL),
('gpt-3', 'Business EDA Strategist', 'Expert guide for Exploratory Data Analysis in a business context.', 'Link', 'https://chatgpt.com/g/g-6968b08a396c81919e4cf41c318595a1-business-eda-strategist', 'Gems GPTs', 'AI Tools', NULL),
('gpt-4', 'Syllabrix', 'AI-powered syllabus and curriculum builder.', 'Link', 'https://chatgpt.com/g/g-69624841e9808191847e5f0682c8a6de-syllabrix', 'Gems GPTs', 'AI Tools', NULL),
('gpt-5', 'NoteSmith', 'Smart note-taking and summarization assistant.', 'Link', 'https://chatgpt.com/g/g-6962605ee32481918f2c0ee70c521b90-notesmith', 'Gems GPTs', 'AI Tools', NULL),
('gpt-6', 'HumanForge', 'AI-powered human resource and team building assistant.', 'Link', 'https://chatgpt.com/g/g-696e0b31d42081918957b4e6855c006b-humanforge', 'Gems GPTs', 'AI Tools', NULL),

INSERT INTO semesters (id, program_id, name, short_name, number, academic_year, is_active) VALUES
('b2c3d4e5-0001-0000-0000-000000000001', 'a1b2c3d4-0001-0000-0000-000000000001', 'Semester 1 (Jul-Nov)', 'Sem 1', 1, NULL, false),
('c3d4e5f6-0002-0000-0000-000000000002', 'a1b2c3d4-0001-0000-0000-000000000001', 'Semester 2 (Jan-May)', 'Sem 2', 2, NULL, true),
('d4e5f6a7-0003-0000-0000-000000000003', 'a1b2c3d4-0001-0000-0000-000000000001', 'Semester 3 (Jul-Nov)', 'Sem 3', 3, NULL, false);

-- From INTERVIEW_RESOURCES (interview-resources.ts)
('int-1', '100 Excel Interview Questions And Answers', 'Comprehensive guide for Excel interview preparation.', 'PDF', 'https://drive.google.com/file/d/1lIUt2lUcjGKbbEYtTM4RiRdty-J7RZg1/preview', 'Interview Prep', 'Excel', NULL),
('int-2', '100 Python Interview Questions - Part 1', 'Foundational Python interview questions.', 'PDF', 'https://drive.google.com/file/d/1qIBWFzWq2rD4z_kiF05_helUfraStbc7/preview', 'Interview Prep', 'Python', NULL),
('int-3', '140+ Basic Python Programs', 'Practice programs to build coding logic.', 'PDF', 'https://drive.google.com/file/d/1jJXhW3z-GrUFz19XBNHEiSFI3kYNk5k0/preview', 'Interview Prep', 'Python', NULL),
('int-4', '230+ PowerBI Interview Questions', 'Massive collection of PowerBI interview Q&A.', 'PDF', 'https://drive.google.com/file/d/1QuHSoFz8Ex4MAC-5sOgp2ErbVZFKGHFj/preview', 'Interview Prep', 'Power BI', NULL),
('int-5', '800+ SQL Interview Queries', 'Extensive SQL query collection for interviews.', 'PDF', 'https://drive.google.com/file/d/1ERoSzUWgXqSxAkJ2bTNoCogX4bk8Vlvg/preview', 'Interview Prep', 'SQL', NULL),
('int-6', 'Accenture Data Analyst Interview Questions', 'Company-specific interview questions for Accenture.', 'PDF', 'https://drive.google.com/file/d/1r40lE-scLqGu7APCTLb6SmsFKZSU43C5/preview', 'Interview Prep', 'Company Specific', NULL),
('int-7', 'Amazon & Myntra Data Analyst Interview Questions', 'Real interview questions from top tech giants.', 'PDF', 'https://drive.google.com/file/d/1eVF7AgGEEkhdkKYXh6EP1HkeTuri9B9C/preview', 'Interview Prep', 'Company Specific', NULL),
('int-8', 'Amazon Data Analyst Interview Questions', 'Focused preparation for Amazon DA roles.', 'PDF', 'https://drive.google.com/file/d/1GkYzW-m5i1nIvi1qBVFB8uU1a9dK68qe/preview', 'Interview Prep', 'Company Specific', NULL),
('int-9', 'American Express Data Analyst Interview QnA', 'Interview guide for American Express.', 'PDF', 'https://drive.google.com/file/d/14ngSL6cm4DFuopwqrIvk1cif5YJyrwdR/preview', 'Interview Prep', 'Company Specific', NULL),
('int-10', 'Blinkit & Zepto Interview Questions', 'Questions from quick-commerce leaders.', 'PDF', 'https://drive.google.com/file/d/1Qpq3t1qkNLPGaKxoxq8nMlbUASvemF3R/preview', 'Interview Prep', 'Company Specific', NULL),
('int-11', 'Blinkit Power BI Developer Interview Questions', 'Power BI specific questions for Blinkit.', 'PDF', 'https://drive.google.com/file/d/1jDTGVR-BaAA-RMUlPreFdaK1EgAmBS1-/preview', 'Interview Prep', 'Company Specific', NULL),
('int-12', 'Cognizant Data Analyst Interview Questions', 'Preparation material for Cognizant.', 'PDF', 'https://drive.google.com/file/d/1nQsUxHTWAN7g4zOpX_iZQHfUu6FHClu5/preview', 'Interview Prep', 'Company Specific', NULL),
('int-13', 'Cognizant Data Analyst Interview Questions Part 2', 'Part 2 of Cognizant interview series.', 'PDF', 'https://drive.google.com/file/d/17STBZTG5yLEjNyET0I9RXmWH6rS1hlID/preview', 'Interview Prep', 'Company Specific', NULL),
('int-14', 'Deloitte Data Analyst Interview Questions', 'Big 4 interview preparation guide.', 'PDF', 'https://drive.google.com/file/d/1_fwE9nAO_sBl8akYeOdhBoPbzxaRv4Qk/preview', 'Interview Prep', 'Company Specific', NULL),
('int-15', 'Excel Formulas for Data Analysts', 'Essential formulas cheat sheet.', 'PDF', 'https://drive.google.com/file/d/1s3BqsIIJxwCf1xyoA5qzFvjDTftWp1Fh/preview', 'Interview Prep', 'Excel', NULL),
('int-16', 'Exl Latest Data Analyst Interviews Questions', 'Latest questions from recent interviews.', 'PDF', 'https://drive.google.com/file/d/1RZjkeBLaXkP-LJsvBtCLywAzV9Y8kaLE/preview', 'Interview Prep', 'General', NULL),
('int-17', 'Flipkart & Zomato Data Analyst Interview Questions', 'Questions from top Indian startups.', 'PDF', 'https://drive.google.com/file/d/1fJz5Na9DVDM6TmGnbT547gjz6oHYg91q/preview', 'Interview Prep', 'Company Specific', NULL),
('int-18', 'Flipkart Data Analyst Interview Questions', 'Targeted Flipkart interview prep.', 'PDF', 'https://drive.google.com/file/d/1ezyK2H62wOxPXVMgclXk7MtZ00gUNCuT/preview', 'Interview Prep', 'Company Specific', NULL),
('int-19', 'Ford Motor Data Analyst Interview Questions', 'Automotive sector analytics questions.', 'PDF', 'https://drive.google.com/file/d/1w_B34dxOUlBmWcyYRfPzSfCmDVuZqyD_/preview', 'Interview Prep', 'Company Specific', NULL),
('int-20', 'Goldman Sachs Python Interview Questions', 'High-level Python questions for finance.', 'PDF', 'https://drive.google.com/file/d/1beeHsop455mqV6WzGn7nDqEAEFqvsoff/preview', 'Interview Prep', 'Company Specific', NULL),
('int-21', 'Google Data Analyst Interview Questions', 'Prep for the Google interview process.', 'PDF', 'https://drive.google.com/file/d/1pfMvHKCGm2xBeHGQelu1gZ3s3W_4BD85/preview', 'Interview Prep', 'Company Specific', NULL),
('int-22', 'HCL Power BI Developer Interview Questions', 'HCL specific Power BI questions.', 'PDF', 'https://drive.google.com/file/d/1PQW61UPjb-nUOHp4sVoX2_qkqLGdG6Er/preview', 'Interview Prep', 'Company Specific', NULL),
('int-23', 'KPMG Data Analyst Interview Questions - Part 1', 'KPMG interview series Part 1.', 'PDF', 'https://drive.google.com/file/d/1cFPm5rJnei2saBxKUuqIr3LNAhpu9D4L/preview', 'Interview Prep', 'Company Specific', NULL),
('int-24', 'KPMG Data Analyst Interview Questions', 'Comprehensive KPMG questions.', 'PDF', 'https://drive.google.com/file/d/15C6ywWnOtn5uXa_r5JTuHspGMstm7AAZ/preview', 'Interview Prep', 'Company Specific', NULL),
('int-25', 'LeetCode Problems', 'Collection of relevant LeetCode problems.', 'PDF', 'https://drive.google.com/file/d/1wh5b2z3UJlIA5TVn-rHu94A6BmwA3l58/preview', 'Interview Prep', 'Coding', NULL),
('int-26', 'Myntra Data Analyst Interview Questions', 'Fashion e-commerce analytics questions.', 'PDF', 'https://drive.google.com/file/d/19ZrStwWNvpOrbGCdPbK1xzvZ44Xped_j/preview', 'Interview Prep', 'Company Specific', NULL),
('int-27', 'Most Asked SQL Interview Questions at MAANG', 'Top SQL questions for major tech companies.', 'PDF', 'https://drive.google.com/file/d/1s7HBlGEITsxSa37e0UfrGYW3w8qW95sL/preview', 'Interview Prep', 'SQL', NULL),
('int-28', 'PhonePe Data Analyst Interview Questions', 'Fintech interview questions.', 'PDF', 'https://drive.google.com/file/d/12OmsAW2W_hQixvpcCmdxqhB5DB7wbXJ7/preview', 'Interview Prep', 'Company Specific', NULL),
('int-29', 'Policy Bazaar Data Analyst Interview Questions', 'Insurance tech interview questions.', 'PDF', 'https://drive.google.com/file/d/18M8xT7oE4_rurDaz45gPi5LiTMit20Ex/preview', 'Interview Prep', 'Company Specific', NULL),
('int-30', 'Power BI Interview 50 Questions', 'Top 50 Power BI questions.', 'PDF', 'https://drive.google.com/file/d/17poz0s1m6fzLSl0lePMKp0nQv3SWmyyT/preview', 'Interview Prep', 'Power BI', NULL),
('int-31', 'Power BI Interview Guide', 'A complete guide to ace Power BI interviews.', 'PDF', 'https://drive.google.com/file/d/1dG7OWa-vmOJZAyBvg_wm14891vukHfI1/preview', 'Interview Prep', 'Power BI', NULL),
('int-32', 'Power BI Interview Kit', 'All-in-one kit for Power BI.', 'PDF', 'https://drive.google.com/file/d/1IusO6ygyvaoKdZbsmz1ZXGcP-f44gj6e/preview', 'Interview Prep', 'Power BI', NULL),
('int-33', 'Power BI Interview QnA', 'Q&A format for quick revision.', 'PDF', 'https://drive.google.com/file/d/1oMTBGrWkijt-hihQ0xvwKCEp_mdbXtV0/preview', 'Interview Prep', 'Power BI', NULL),
('int-34', 'SQL 300 Interview Questions - Part 1', 'First part of a massive SQL question bank.', 'PDF', 'https://drive.google.com/file/d/10AwpWq_ljmZDgBl7LWWY9735wXK9Vgx7/preview', 'Interview Prep', 'SQL', NULL),
('int-35', 'SQL Case Studies: Flipkart & Zomato', 'Real-world SQL case studies.', 'PDF', 'https://drive.google.com/file/d/14h_HlmvQE9oscnxGvKSd01mqR3vONDj-/preview', 'Interview Prep', 'SQL', NULL),
('int-36', 'SQL Interview Questions & Answers', 'Standard SQL Q&A.', 'PDF', 'https://drive.google.com/file/d/1A1zsfRGZRcdV8RruEg5nCJd7-1Cjp1yv/preview', 'Interview Prep', 'SQL', NULL),
('int-37', 'SQL Interview Questions - Part 2', 'Advanced SQL questions.', 'PDF', 'https://drive.google.com/file/d/1bcNueR-TzGTwKEyNmOaN9T_gHGCO6dPJ/preview', 'Interview Prep', 'SQL', NULL),
('int-38', 'SQL Interview Vault: 70 Real-World Scenarios', 'Scenario-based SQL questions.', 'PDF', 'https://drive.google.com/file/d/1M_r9TGhK2vWML3V4iWls_DCGzVOIifLm/preview', 'Interview Prep', 'SQL', NULL),
('int-39', 'SQL Interview Kit', 'Complete kit for SQL interviews.', 'PDF', 'https://drive.google.com/file/d/1fRLfjv1ulZyVd9pMDAjsO2dOdfbwJjZ-/preview', 'Interview Prep', 'SQL', NULL),
('int-40', 'TCS Data Analyst Interview Questions 2025', 'Latest TCS interview pattern.', 'PDF', 'https://drive.google.com/file/d/1qg3RZUzM3upu_cd_6R4EISvPNPcNmfpp/preview', 'Interview Prep', 'Company Specific', NULL),
('int-41', 'TCS Data Analyst Interview Questions Ref', 'Additional TCS reference material.', 'PDF', 'https://drive.google.com/file/d/1NnMBZsH2BYzw-Jkw-4PYiuFJ-GaIO3rN/preview', 'Interview Prep', 'Company Specific', NULL),
('int-42', 'Tiger Analytics Power BI Developer Interview Questions', 'Questions from Tiger Analytics.', 'PDF', 'https://drive.google.com/file/d/1KcskwXTWw6fFqbvdRHXuis-rYE4MLGsm/preview', 'Interview Prep', 'Company Specific', NULL),
('int-43', 'Top 150 Python Interview Questions', 'Common python questions with solutions.', 'PDF', 'https://drive.google.com/file/d/1yP8PumdcxaV_DOSXWMNb8-XFvRSkQSXH/preview', 'Interview Prep', 'Python', NULL),
('int-44', 'Wipro Data Analyst Interview Questions', 'Wipro specific interview questions.', 'PDF', 'https://drive.google.com/file/d/1ixFmByPHykORdOD6iHKTSm4MJd5Ka8by/preview', 'Interview Prep', 'Company Specific', NULL),
('int-45', 'Zomato SQL Interview Questions', 'Food tech SQL questions.', 'PDF', 'https://drive.google.com/file/d/1Y5mNmkJp4devg341I_xoFAHADYklZl_0/preview', 'Interview Prep', 'Company Specific', NULL);
