-- ==========================================
-- YouTube Videos for PBA212
-- Data Analysis Power BI
-- Subject ID: pba212
-- Table: youtube_library
-- ==========================================

INSERT INTO youtube_library (subject_id, unit_id, title, url, tags) VALUES

-- ── Unit 1: Power BI Introduction ─────────────────────────────────
('pba212', 'unit-1', 'Data Visualization', 'https://www.youtube.com/results?search_query=Data+Visualization+fundamentals+for+business+analytics', ARRAY['unit-1', 'data visualization']),
('pba212', 'unit-1', 'Reporting', 'https://www.youtube.com/results?search_query=Business+Reporting+and+Data+Reporting+concepts', ARRAY['unit-1', 'reporting', 'business reporting']),
('pba212', 'unit-1', 'Business Intelligence (BI)', 'https://www.youtube.com/results?search_query=Business+Intelligence+complete+course+for+beginners', ARRAY['unit-1', 'BI', 'business intelligence']),
('pba212', 'unit-1', 'Traditional BI', 'https://www.youtube.com/results?search_query=Traditional+Business+Intelligence+architecture+explained', ARRAY['unit-1', 'traditional BI']),
('pba212', 'unit-1', 'Self-Service BI', 'https://www.youtube.com/results?search_query=Self+Service+BI+concepts+and+benefits', ARRAY['unit-1', 'self-service BI']),
('pba212', 'unit-1', 'Cloud-Based BI', 'https://www.youtube.com/results?search_query=Cloud+Based+Business+Intelligence+platforms', ARRAY['unit-1', 'cloud BI']),
('pba212', 'unit-1', 'On-Premise BI', 'https://www.youtube.com/results?search_query=On+Premise+BI+vs+Cloud+BI+explained', ARRAY['unit-1', 'on-premise BI']),
('pba212', 'unit-1', 'Power BI Products', 'https://www.youtube.com/results?search_query=Microsoft+Power+BI+ecosystem+overview', ARRAY['unit-1', 'power bi products']),
('pba212', 'unit-1', 'Power BI Desktop', 'https://www.youtube.com/results?search_query=Power+BI+Desktop+complete+tutorial', ARRAY['unit-1', 'power bi desktop']),
('pba212', 'unit-1', 'Power Query', 'https://www.youtube.com/results?search_query=Power+Query+beginner+to+advanced+tutorial', ARRAY['unit-1', 'power query']),
('pba212', 'unit-1', 'Power Pivot', 'https://www.youtube.com/results?search_query=Power+Pivot+complete+tutorial', ARRAY['unit-1', 'power pivot']),
('pba212', 'unit-1', 'Power View', 'https://www.youtube.com/results?search_query=Power+View+in+Power+BI+explained', ARRAY['unit-1', 'power view']),
('pba212', 'unit-1', 'Flow of Work in Power BI Desktop', 'https://www.youtube.com/results?search_query=Power+BI+workflow+from+data+import+to+dashboard', ARRAY['unit-1', 'workflow', 'power bi desktop']),
('pba212', 'unit-1', 'Power BI Report Server', 'https://www.youtube.com/results?search_query=Power+BI+Report+Server+tutorial', ARRAY['unit-1', 'report server']),
('pba212', 'unit-1', 'Power BI Service', 'https://www.youtube.com/results?search_query=Power+BI+Service+complete+guide', ARRAY['unit-1', 'power bi service']),
('pba212', 'unit-1', 'Power BI Mobile', 'https://www.youtube.com/results?search_query=Power+BI+Mobile+app+tutorial', ARRAY['unit-1', 'power bi mobile']),
('pba212', 'unit-1', 'Power BI Architecture', 'https://www.youtube.com/results?search_query=Power+BI+architecture+explained', ARRAY['unit-1', 'architecture']),
('pba212', 'unit-1', 'History of Power BI', 'https://www.youtube.com/results?search_query=Evolution+and+history+of+Microsoft+Power+BI', ARRAY['unit-1', 'history']),

-- ── Unit 2: Power Query and Data Transformation ───────────────────
('pba212', 'unit-2', 'Data Transformation', 'https://www.youtube.com/results?search_query=Data+Transformation+in+Power+BI+complete+tutorial', ARRAY['unit-2', 'data transformation']),
('pba212', 'unit-2', 'Benefits of Data Transformation', 'https://www.youtube.com/results?search_query=Why+Data+Transformation+is+important+in+Power+BI', ARRAY['unit-2', 'benefits of transformation']),
('pba212', 'unit-2', 'Shape and Transform Data', 'https://www.youtube.com/results?search_query=Shape+and+Transform+Data+using+Power+Query', ARRAY['unit-2', 'shape data']),
('pba212', 'unit-2', 'Overview of Power Query', 'https://www.youtube.com/results?search_query=Power+Query+overview+for+beginners', ARRAY['unit-2', 'power query overview']),
('pba212', 'unit-2', 'Query Editor', 'https://www.youtube.com/results?search_query=Power+Query+Editor+tutorial', ARRAY['unit-2', 'query editor']),
('pba212', 'unit-2', 'Query Editor User Interface', 'https://www.youtube.com/results?search_query=Power+Query+Editor+interface+explained', ARRAY['unit-2', 'query editor UI']),
('pba212', 'unit-2', 'Home Tab', 'https://www.youtube.com/results?search_query=Power+Query+Home+Tab+tutorial', ARRAY['unit-2', 'home tab']),
('pba212', 'unit-2', 'Transform Tab', 'https://www.youtube.com/results?search_query=Power+Query+Transform+Tab+explained', ARRAY['unit-2', 'transform tab']),
('pba212', 'unit-2', 'Add Column Tab', 'https://www.youtube.com/results?search_query=Power+Query+Add+Column+Tab+tutorial', ARRAY['unit-2', 'add column tab']),
('pba212', 'unit-2', 'View Tab', 'https://www.youtube.com/results?search_query=Power+Query+View+Tab+explained', ARRAY['unit-2', 'view tab']),
('pba212', 'unit-2', 'Queries Pane', 'https://www.youtube.com/results?search_query=Power+Query+Queries+Pane+guide', ARRAY['unit-2', 'queries pane']),
('pba212', 'unit-2', 'Data View / Results Pane', 'https://www.youtube.com/results?search_query=Power+Query+Data+View+and+Results+Pane', ARRAY['unit-2', 'data view', 'results pane']),
('pba212', 'unit-2', 'Query Settings Pane', 'https://www.youtube.com/results?search_query=Query+Settings+Pane+Power+Query', ARRAY['unit-2', 'query settings pane']),
('pba212', 'unit-2', 'Formula Bar', 'https://www.youtube.com/results?search_query=Formula+Bar+in+Power+Query+explained', ARRAY['unit-2', 'formula bar']),
('pba212', 'unit-2', 'Saving Work in Power BI', 'https://www.youtube.com/results?search_query=Saving+and+managing+Power+BI+projects', ARRAY['unit-2', 'saving work']),
('pba212', 'unit-2', 'Data Types', 'https://www.youtube.com/results?search_query=Data+Types+in+Power+Query', ARRAY['unit-2', 'data types']),
('pba212', 'unit-2', 'Changing Column Data Types', 'https://www.youtube.com/results?search_query=Change+Data+Type+in+Power+Query', ARRAY['unit-2', 'change data types']),
('pba212', 'unit-2', 'Auto Filter and Basic Filtering', 'https://www.youtube.com/results?search_query=Power+Query+filtering+basics', ARRAY['unit-2', 'auto filter']),
('pba212', 'unit-2', 'Text Filters', 'https://www.youtube.com/results?search_query=Power+Query+text+filters+tutorial', ARRAY['unit-2', 'text filters']),
('pba212', 'unit-2', 'Number Filters', 'https://www.youtube.com/results?search_query=Power+Query+number+filters+tutorial', ARRAY['unit-2', 'number filters']),
('pba212', 'unit-2', 'Date Filters', 'https://www.youtube.com/results?search_query=Power+Query+date+filters+explained', ARRAY['unit-2', 'date filters']),
('pba212', 'unit-2', 'Filter Multiple Columns', 'https://www.youtube.com/results?search_query=Power+Query+multiple+column+filtering', ARRAY['unit-2', 'filter multiple columns']),
('pba212', 'unit-2', 'Remove Columns', 'https://www.youtube.com/results?search_query=Remove+Columns+in+Power+Query', ARRAY['unit-2', 'remove columns']),
('pba212', 'unit-2', 'Remove Other Columns', 'https://www.youtube.com/results?search_query=Remove+Other+Columns+Power+Query+tutorial', ARRAY['unit-2', 'remove other columns']),
('pba212', 'unit-2', 'Name and Rename Columns', 'https://www.youtube.com/results?search_query=Rename+Columns+in+Power+Query', ARRAY['unit-2', 'rename columns']),
('pba212', 'unit-2', 'Reorder Columns', 'https://www.youtube.com/results?search_query=Reorder+Columns+Power+Query', ARRAY['unit-2', 'reorder columns']),
('pba212', 'unit-2', 'Sort Columns', 'https://www.youtube.com/results?search_query=Sort+Data+in+Power+Query', ARRAY['unit-2', 'sort columns']),
('pba212', 'unit-2', 'Add Custom Column', 'https://www.youtube.com/results?search_query=Custom+Column+in+Power+Query', ARRAY['unit-2', 'custom column']),
('pba212', 'unit-2', 'Split Columns', 'https://www.youtube.com/results?search_query=Split+Columns+Power+Query+tutorial', ARRAY['unit-2', 'split columns']),
('pba212', 'unit-2', 'Merge Columns', 'https://www.youtube.com/results?search_query=Merge+Columns+in+Power+Query', ARRAY['unit-2', 'merge columns']),
('pba212', 'unit-2', 'Pivot Columns', 'https://www.youtube.com/results?search_query=Pivot+Columns+Power+Query+tutorial', ARRAY['unit-2', 'pivot columns']),
('pba212', 'unit-2', 'Unpivot Columns', 'https://www.youtube.com/results?search_query=Unpivot+Columns+Power+Query+explained', ARRAY['unit-2', 'unpivot columns']),
('pba212', 'unit-2', 'Transpose Columns', 'https://www.youtube.com/results?search_query=Transpose+Data+in+Power+Query', ARRAY['unit-2', 'transpose columns']),

-- ── Unit 3: Data Modeling ─────────────────────────────────────────
('pba212', 'unit-3', 'Introduction to Data Modeling', 'https://www.youtube.com/results?search_query=Data+Modeling+in+Power+BI+complete+tutorial', ARRAY['unit-3', 'data modeling']),
('pba212', 'unit-3', 'Relationships', 'https://www.youtube.com/results?search_query=Relationships+in+Power+BI+explained', ARRAY['unit-3', 'relationships']),
('pba212', 'unit-3', 'Need for Relationships', 'https://www.youtube.com/results?search_query=Why+relationships+are+important+in+Power+BI', ARRAY['unit-3', 'need for relationships']),
('pba212', 'unit-3', 'Relationship Types / Cardinality', 'https://www.youtube.com/results?search_query=Cardinality+and+relationships+in+Power+BI', ARRAY['unit-3', 'cardinality']),
('pba212', 'unit-3', 'One-to-One Relationship', 'https://www.youtube.com/results?search_query=One+to+One+relationship+Power+BI', ARRAY['unit-3', 'one-to-one']),
('pba212', 'unit-3', 'One-to-Many Relationship', 'https://www.youtube.com/results?search_query=One+to+Many+relationship+Power+BI', ARRAY['unit-3', 'one-to-many']),
('pba212', 'unit-3', 'Many-to-Many Relationship', 'https://www.youtube.com/results?search_query=Many+to+Many+relationship+Power+BI', ARRAY['unit-3', 'many-to-many']),
('pba212', 'unit-3', 'Auto Detect Relationships', 'https://www.youtube.com/results?search_query=Auto+Detect+Relationships+in+Power+BI', ARRAY['unit-3', 'auto detect relationships']),
('pba212', 'unit-3', 'Create New Relationships', 'https://www.youtube.com/results?search_query=Creating+relationships+in+Power+BI', ARRAY['unit-3', 'create relationships']),
('pba212', 'unit-3', 'Edit Existing Relationships', 'https://www.youtube.com/results?search_query=Editing+relationships+in+Power+BI', ARRAY['unit-3', 'edit relationships']),
('pba212', 'unit-3', 'Active and Inactive Relationships', 'https://www.youtube.com/results?search_query=Active+vs+Inactive+Relationships+Power+BI', ARRAY['unit-3', 'active inactive relationships']),
('pba212', 'unit-3', 'Delete Relationships', 'https://www.youtube.com/results?search_query=Deleting+relationships+in+Power+BI', ARRAY['unit-3', 'delete relationships']),

-- ── Unit 4: DAX (Data Analysis Expressions) ───────────────────────
('pba212', 'unit-4', 'What is DAX', 'https://www.youtube.com/results?search_query=DAX+basics+in+Power+BI+complete+tutorial', ARRAY['unit-4', 'DAX', 'what is DAX']),
('pba212', 'unit-4', 'Calculated Columns', 'https://www.youtube.com/results?search_query=Calculated+Columns+in+Power+BI+explained', ARRAY['unit-4', 'calculated columns']),
('pba212', 'unit-4', 'Measures', 'https://www.youtube.com/results?search_query=Measures+in+Power+BI+complete+guide', ARRAY['unit-4', 'measures']),
('pba212', 'unit-4', 'DAX Table and Column Name Syntax', 'https://www.youtube.com/results?search_query=DAX+syntax+and+naming+conventions', ARRAY['unit-4', 'DAX syntax']),
('pba212', 'unit-4', 'Creating Calculated Columns', 'https://www.youtube.com/results?search_query=Create+Calculated+Columns+in+Power+BI', ARRAY['unit-4', 'creating calculated columns']),
('pba212', 'unit-4', 'Creating Measures', 'https://www.youtube.com/results?search_query=Create+Measures+in+Power+BI', ARRAY['unit-4', 'creating measures']),
('pba212', 'unit-4', 'Calculated Columns vs Measures', 'https://www.youtube.com/results?search_query=Calculated+Columns+vs+Measures+Power+BI', ARRAY['unit-4', 'columns vs measures']),
('pba212', 'unit-4', 'DAX Syntax and Operators', 'https://www.youtube.com/results?search_query=DAX+syntax+and+operators+tutorial', ARRAY['unit-4', 'DAX operators']),
('pba212', 'unit-4', 'Arithmetic Operators', 'https://www.youtube.com/results?search_query=DAX+arithmetic+operators+explained', ARRAY['unit-4', 'arithmetic operators']),
('pba212', 'unit-4', 'Comparison Operators', 'https://www.youtube.com/results?search_query=DAX+comparison+operators+tutorial', ARRAY['unit-4', 'comparison operators']),
('pba212', 'unit-4', 'Text Concatenation Operator', 'https://www.youtube.com/results?search_query=DAX+text+concatenation+examples', ARRAY['unit-4', 'text concatenation']),
('pba212', 'unit-4', 'Logical Operators', 'https://www.youtube.com/results?search_query=DAX+logical+operators+explained', ARRAY['unit-4', 'logical operators']),
('pba212', 'unit-4', 'Date and Time Functions', 'https://www.youtube.com/results?search_query=DAX+date+and+time+functions+tutorial', ARRAY['unit-4', 'date time functions']),
('pba212', 'unit-4', 'Text Functions', 'https://www.youtube.com/results?search_query=DAX+text+functions+explained', ARRAY['unit-4', 'text functions']),
('pba212', 'unit-4', 'Logical Functions', 'https://www.youtube.com/results?search_query=DAX+logical+functions+complete+guide', ARRAY['unit-4', 'logical functions']),
('pba212', 'unit-4', 'Math and Statistical Functions', 'https://www.youtube.com/results?search_query=DAX+mathematical+and+statistical+functions', ARRAY['unit-4', 'math statistical functions']),
('pba212', 'unit-4', 'Filter Functions', 'https://www.youtube.com/results?search_query=DAX+filter+functions+tutorial', ARRAY['unit-4', 'filter functions']),

-- ── Unit 5: Visualizations and Dashboards ─────────────────────────
('pba212', 'unit-5', 'Visualizing Data', 'https://www.youtube.com/results?search_query=Power+BI+data+visualization+best+practices', ARRAY['unit-5', 'visualizing data']),
('pba212', 'unit-5', 'Why Visualizations', 'https://www.youtube.com/results?search_query=Importance+of+data+visualization+in+BI', ARRAY['unit-5', 'why visualizations']),
('pba212', 'unit-5', 'Visualization Types', 'https://www.youtube.com/results?search_query=Power+BI+visualization+types+overview', ARRAY['unit-5', 'visualization types']),
('pba212', 'unit-5', 'Bar and Column Charts', 'https://www.youtube.com/results?search_query=Power+BI+Bar+and+Column+Charts+tutorial', ARRAY['unit-5', 'bar charts', 'column charts']),
('pba212', 'unit-5', 'Stacked Bar Chart', 'https://www.youtube.com/results?search_query=Power+BI+Stacked+Bar+Chart', ARRAY['unit-5', 'stacked bar chart']),
('pba212', 'unit-5', 'Stacked Column Chart', 'https://www.youtube.com/results?search_query=Power+BI+Stacked+Column+Chart', ARRAY['unit-5', 'stacked column chart']),
('pba212', 'unit-5', 'Clustered Bar Chart', 'https://www.youtube.com/results?search_query=Power+BI+Clustered+Bar+Chart', ARRAY['unit-5', 'clustered bar chart']),
('pba212', 'unit-5', 'Clustered Column Chart', 'https://www.youtube.com/results?search_query=Power+BI+Clustered+Column+Chart', ARRAY['unit-5', 'clustered column chart']),
('pba212', 'unit-5', '100% Stacked Bar Chart', 'https://www.youtube.com/results?search_query=Power+BI+100+Percent+Stacked+Bar+Chart', ARRAY['unit-5', '100% stacked bar chart']),
('pba212', 'unit-5', '100% Stacked Column Chart', 'https://www.youtube.com/results?search_query=Power+BI+100+Percent+Stacked+Column+Chart', ARRAY['unit-5', '100% stacked column chart']),
('pba212', 'unit-5', 'Pie Charts', 'https://www.youtube.com/results?search_query=Power+BI+Pie+Chart+tutorial', ARRAY['unit-5', 'pie charts']),
('pba212', 'unit-5', 'Donut Charts', 'https://www.youtube.com/results?search_query=Power+BI+Donut+Chart+tutorial', ARRAY['unit-5', 'donut charts']),
('pba212', 'unit-5', 'Scatter Charts', 'https://www.youtube.com/results?search_query=Power+BI+Scatter+Chart+explained', ARRAY['unit-5', 'scatter charts']),
('pba212', 'unit-5', 'Table Visual', 'https://www.youtube.com/results?search_query=Power+BI+Table+Visual+tutorial', ARRAY['unit-5', 'table visual']),
('pba212', 'unit-5', 'Matrix Visualization', 'https://www.youtube.com/results?search_query=Power+BI+Matrix+Visual+explained', ARRAY['unit-5', 'matrix visualization']),
('pba212', 'unit-5', 'Line Charts', 'https://www.youtube.com/results?search_query=Power+BI+Line+Chart+tutorial', ARRAY['unit-5', 'line charts']),
('pba212', 'unit-5', 'Area Charts', 'https://www.youtube.com/results?search_query=Power+BI+Area+Chart+tutorial', ARRAY['unit-5', 'area charts']),
('pba212', 'unit-5', 'Stacked Area Charts', 'https://www.youtube.com/results?search_query=Power+BI+Stacked+Area+Chart', ARRAY['unit-5', 'stacked area charts']),
('pba212', 'unit-5', 'Combo Charts', 'https://www.youtube.com/results?search_query=Power+BI+Combo+Chart+tutorial', ARRAY['unit-5', 'combo charts']),
('pba212', 'unit-5', 'Line and Stacked Column Chart', 'https://www.youtube.com/results?search_query=Power+BI+Line+and+Stacked+Column+Chart', ARRAY['unit-5', 'line and stacked column chart']),
('pba212', 'unit-5', 'Line and Clustered Column Chart', 'https://www.youtube.com/results?search_query=Power+BI+Line+and+Clustered+Column+Chart', ARRAY['unit-5', 'line and clustered column chart']),
('pba212', 'unit-5', 'Ribbon Chart', 'https://www.youtube.com/results?search_query=Power+BI+Ribbon+Chart+tutorial', ARRAY['unit-5', 'ribbon chart']),
('pba212', 'unit-5', 'Waterfall Chart', 'https://www.youtube.com/results?search_query=Power+BI+Waterfall+Chart+explained', ARRAY['unit-5', 'waterfall chart']),
('pba212', 'unit-5', 'Funnel Chart', 'https://www.youtube.com/results?search_query=Power+BI+Funnel+Chart+tutorial', ARRAY['unit-5', 'funnel chart']),
('pba212', 'unit-5', 'Advantages of Dashboards', 'https://www.youtube.com/results?search_query=Benefits+of+Power+BI+Dashboards', ARRAY['unit-5', 'advantages of dashboards', 'benefits']),
('pba212', 'unit-5', 'Interacting with Dashboards', 'https://www.youtube.com/results?search_query=Power+BI+Dashboard+interactions', ARRAY['unit-5', 'interacting with dashboards']),
('pba212', 'unit-5', 'Formatting Dashboards', 'https://www.youtube.com/results?search_query=Power+BI+Dashboard+formatting+techniques', ARRAY['unit-5', 'formatting dashboards']),
('pba212', 'unit-5', 'Sharing Dashboards', 'https://www.youtube.com/results?search_query=Publishing+and+sharing+Power+BI+dashboards', ARRAY['unit-5', 'sharing dashboards'])

ON CONFLICT DO NOTHING;
