-- Insert BOTH Study Notes and Revision Notes for Sem-2
-- This script restores both types of notes if they were deleted.

INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba204', 'unit-1', 'study_note', 'Unit 1: Production and Operations Management', 'https://curriculab-resources.netlify.app/Sem-2/PBA204%20Production%20and%20Operations%20Management/PBA204%20Unit-1%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba204', 'unit-1', 'revision_note', 'Unit 1 Revision Notes', 'https://curriculab-resources.netlify.app/Sem-2/PBA204%20Production%20and%20Operations%20Management/PBA204%20Unit-1%20Revision%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba204', 'unit-2', 'study_note', 'Unit 2: Production and Operations Management', 'https://curriculab-resources.netlify.app/Sem-2/PBA204%20Production%20and%20Operations%20Management/PBA204%20Unit-2%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba204', 'unit-2', 'revision_note', 'Unit 2 Revision Notes', 'https://curriculab-resources.netlify.app/Sem-2/PBA204%20Production%20and%20Operations%20Management/PBA204%20Unit-2%20Revision%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba204', 'unit-3', 'study_note', 'Unit 3: Production and Operations Management', 'https://curriculab-resources.netlify.app/Sem-2/PBA204%20Production%20and%20Operations%20Management/PBA204%20Unit-3%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba204', 'unit-3', 'revision_note', 'Unit 3 Revision Notes', 'https://curriculab-resources.netlify.app/Sem-2/PBA204%20Production%20and%20Operations%20Management/PBA204%20Unit-3%20Revision%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba204', 'unit-4', 'study_note', 'Unit 4: Production and Operations Management', 'https://curriculab-resources.netlify.app/Sem-2/PBA204%20Production%20and%20Operations%20Management/PBA204%20Unit-4%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba204', 'unit-4', 'revision_note', 'Unit 4 Revision Notes', 'https://curriculab-resources.netlify.app/Sem-2/PBA204%20Production%20and%20Operations%20Management/PBA204%20Unit-4%20Revision%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba204', 'unit-5', 'study_note', 'Unit 5: Production and Operations Management', 'https://curriculab-resources.netlify.app/Sem-2/PBA204%20Production%20and%20Operations%20Management/PBA204%20Unit-5%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba204', 'unit-5', 'revision_note', 'Unit 5 Revision Notes', 'https://curriculab-resources.netlify.app/Sem-2/PBA204%20Production%20and%20Operations%20Management/PBA204%20Unit-5%20Revision%20Notes.html');

INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba205', 'unit-1', 'study_note', 'Unit 1: Digital Transformation', 'https://curriculab-resources.netlify.app/Sem-2/PBA205%20Digital%20Transformation/PBA205%20Unit-1%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba205', 'unit-1', 'revision_note', 'Unit 1 Revision Notes', 'https://curriculab-resources.netlify.app/Sem-2/PBA205%20Digital%20Transformation/PBA205%20Unit-1%20Revision%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba205', 'unit-2', 'study_note', 'Unit 2: Digital Transformation', 'https://curriculab-resources.netlify.app/Sem-2/PBA205%20Digital%20Transformation/PBA205%20Unit-2%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba205', 'unit-2', 'revision_note', 'Unit 2 Revision Notes', 'https://curriculab-resources.netlify.app/Sem-2/PBA205%20Digital%20Transformation/PBA205%20Unit-2%20Revision%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba205', 'unit-3', 'study_note', 'Unit 3: Digital Transformation', 'https://curriculab-resources.netlify.app/Sem-2/PBA205%20Digital%20Transformation/PBA205%20Unit-3%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba205', 'unit-3', 'revision_note', 'Unit 3 Revision Notes', 'https://curriculab-resources.netlify.app/Sem-2/PBA205%20Digital%20Transformation/PBA205%20Unit-3%20Revision%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba205', 'unit-4', 'study_note', 'Unit 4: Digital Transformation', 'https://curriculab-resources.netlify.app/Sem-2/PBA205%20Digital%20Transformation/PBA205%20Unit-4%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba205', 'unit-4', 'revision_note', 'Unit 4 Revision Notes', 'https://curriculab-resources.netlify.app/Sem-2/PBA205%20Digital%20Transformation/PBA205%20Unit-4%20Revision%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba205', 'unit-5', 'study_note', 'Unit 5: Digital Transformation', 'https://curriculab-resources.netlify.app/Sem-2/PBA205%20Digital%20Transformation/PBA205%20Unit-5%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba205', 'unit-5', 'revision_note', 'Unit 5 Revision Notes', 'https://curriculab-resources.netlify.app/Sem-2/PBA205%20Digital%20Transformation/PBA205%20Unit-5%20Revision%20Notes.html');

INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba206', 'unit-1', 'study_note', 'Unit 1: Legal Aspects of Business', 'https://curriculab-resources.netlify.app/Sem-2/PBA206%20Legal%20Aspects%20of%20Business/PBA206%20Unit-1%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba206', 'unit-1', 'revision_note', 'Unit 1 Revision Notes', 'https://curriculab-resources.netlify.app/Sem-2/PBA206%20Legal%20Aspects%20of%20Business/PBA206%20Unit-1%20Revision%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba206', 'unit-2', 'study_note', 'Unit 2: Legal Aspects of Business', 'https://curriculab-resources.netlify.app/Sem-2/PBA206%20Legal%20Aspects%20of%20Business/PBA206%20Unit-2%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba206', 'unit-2', 'revision_note', 'Unit 2 Revision Notes', 'https://curriculab-resources.netlify.app/Sem-2/PBA206%20Legal%20Aspects%20of%20Business/PBA206%20Unit-2%20Revision%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba206', 'unit-3', 'study_note', 'Unit 3: Legal Aspects of Business', 'https://curriculab-resources.netlify.app/Sem-2/PBA206%20Legal%20Aspects%20of%20Business/PBA206%20Unit-3%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba206', 'unit-3', 'revision_note', 'Unit 3 Revision Notes', 'https://curriculab-resources.netlify.app/Sem-2/PBA206%20Legal%20Aspects%20of%20Business/PBA206%20Unit-3%20Revision%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba206', 'unit-4', 'study_note', 'Unit 4: Legal Aspects of Business', 'https://curriculab-resources.netlify.app/Sem-2/PBA206%20Legal%20Aspects%20of%20Business/PBA206%20Unit-4%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba206', 'unit-4', 'revision_note', 'Unit 4 Revision Notes', 'https://curriculab-resources.netlify.app/Sem-2/PBA206%20Legal%20Aspects%20of%20Business/PBA206%20Unit-4%20Revision%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba206', 'unit-5', 'study_note', 'Unit 5: Legal Aspects of Business', 'https://curriculab-resources.netlify.app/Sem-2/PBA206%20Legal%20Aspects%20of%20Business/PBA206%20Unit-5%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba206', 'unit-5', 'revision_note', 'Unit 5 Revision Notes', 'https://curriculab-resources.netlify.app/Sem-2/PBA206%20Legal%20Aspects%20of%20Business/PBA206%20Unit-5%20Revision%20Notes.html');

INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba207', 'unit-1', 'study_note', 'Unit 1: Visualization and Storytelling', 'https://curriculab-resources.netlify.app/Sem-2/PBA207%20Visualization%20and%20Storytelling/PBA207%20Unit-1%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba207', 'unit-1', 'revision_note', 'Unit 1 Revision Notes', 'https://curriculab-resources.netlify.app/Sem-2/PBA207%20Visualization%20and%20Storytelling/PBA207%20Unit-1%20Revision%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba207', 'unit-2', 'study_note', 'Unit 2: Visualization and Storytelling', 'https://curriculab-resources.netlify.app/Sem-2/PBA207%20Visualization%20and%20Storytelling/PBA207%20Unit-2%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba207', 'unit-2', 'revision_note', 'Unit 2 Revision Notes', 'https://curriculab-resources.netlify.app/Sem-2/PBA207%20Visualization%20and%20Storytelling/PBA207%20Unit-2%20Revision%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba207', 'unit-3', 'study_note', 'Unit 3: Visualization and Storytelling', 'https://curriculab-resources.netlify.app/Sem-2/PBA207%20Visualization%20and%20Storytelling/PBA207%20Unit-3%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba207', 'unit-3', 'revision_note', 'Unit 3 Revision Notes', 'https://curriculab-resources.netlify.app/Sem-2/PBA207%20Visualization%20and%20Storytelling/PBA207%20Unit-3%20Revision%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba207', 'unit-4', 'study_note', 'Unit 4: Visualization and Storytelling', 'https://curriculab-resources.netlify.app/Sem-2/PBA207%20Visualization%20and%20Storytelling/PBA207%20Unit-4%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba207', 'unit-4', 'revision_note', 'Unit 4 Revision Notes', 'https://curriculab-resources.netlify.app/Sem-2/PBA207%20Visualization%20and%20Storytelling/PBA207%20Unit-4%20Revision%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba207', 'unit-5', 'study_note', 'Unit 5: Visualization and Storytelling', 'https://curriculab-resources.netlify.app/Sem-2/PBA207%20Visualization%20and%20Storytelling/PBA207%20Unit-5%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba207', 'unit-5', 'revision_note', 'Unit 5 Revision Notes', 'https://curriculab-resources.netlify.app/Sem-2/PBA207%20Visualization%20and%20Storytelling/PBA207%20Unit-5%20Revision%20Notes.html');

INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba208', 'unit-1', 'study_note', 'Unit 1: Business Research Methods', 'https://curriculab-resources.netlify.app/Sem-2/PBA208%20Business%20Research%20Methods/PBA208%20Unit-1%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba208', 'unit-1', 'revision_note', 'Unit 1 Revision Notes', 'https://curriculab-resources.netlify.app/Sem-2/PBA208%20Business%20Research%20Methods/PBA208%20Unit-1%20Revision%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba208', 'unit-2', 'study_note', 'Unit 2: Business Research Methods', 'https://curriculab-resources.netlify.app/Sem-2/PBA208%20Business%20Research%20Methods/PBA208%20Unit-2%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba208', 'unit-2', 'revision_note', 'Unit 2 Revision Notes', 'https://curriculab-resources.netlify.app/Sem-2/PBA208%20Business%20Research%20Methods/PBA208%20Unit-2%20Revision%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba208', 'unit-3', 'study_note', 'Unit 3: Business Research Methods', 'https://curriculab-resources.netlify.app/Sem-2/PBA208%20Business%20Research%20Methods/PBA208%20Unit-3%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba208', 'unit-3', 'revision_note', 'Unit 3 Revision Notes', 'https://curriculab-resources.netlify.app/Sem-2/PBA208%20Business%20Research%20Methods/PBA208%20Unit-3%20Revision%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba208', 'unit-4', 'study_note', 'Unit 4: Business Research Methods', 'https://curriculab-resources.netlify.app/Sem-2/PBA208%20Business%20Research%20Methods/PBA208%20Unit-4%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba208', 'unit-4', 'revision_note', 'Unit 4 Revision Notes', 'https://curriculab-resources.netlify.app/Sem-2/PBA208%20Business%20Research%20Methods/PBA208%20Unit-4%20Revision%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba208', 'unit-5', 'study_note', 'Unit 5: Business Research Methods', 'https://curriculab-resources.netlify.app/Sem-2/PBA208%20Business%20Research%20Methods/PBA208%20Unit-5%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba208', 'unit-5', 'revision_note', 'Unit 5 Revision Notes', 'https://curriculab-resources.netlify.app/Sem-2/PBA208%20Business%20Research%20Methods/PBA208%20Unit-5%20Revision%20Notes.html');

INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba211', 'unit-1', 'study_note', 'Unit 1: Data Analysis Using Python', 'https://curriculab-resources.netlify.app/Sem-2/PBA211%20Data%20Analysis%20Using%20Python/PBA211%20Unit-1%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba211', 'unit-1', 'revision_note', 'Unit 1 Revision Notes', 'https://curriculab-resources.netlify.app/Sem-2/PBA211%20Data%20Analysis%20Using%20Python/PBA211%20Unit-1%20Revision%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba211', 'unit-2', 'study_note', 'Unit 2: Data Analysis Using Python', 'https://curriculab-resources.netlify.app/Sem-2/PBA211%20Data%20Analysis%20Using%20Python/PBA211%20Unit-2%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba211', 'unit-2', 'revision_note', 'Unit 2 Revision Notes', 'https://curriculab-resources.netlify.app/Sem-2/PBA211%20Data%20Analysis%20Using%20Python/PBA211%20Unit-2%20Revision%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba211', 'unit-3', 'study_note', 'Unit 3: Data Analysis Using Python', 'https://curriculab-resources.netlify.app/Sem-2/PBA211%20Data%20Analysis%20Using%20Python/PBA211%20Unit-3%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba211', 'unit-3', 'revision_note', 'Unit 3 Revision Notes', 'https://curriculab-resources.netlify.app/Sem-2/PBA211%20Data%20Analysis%20Using%20Python/PBA211%20Unit-3%20Revision%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba211', 'unit-4', 'study_note', 'Unit 4: Data Analysis Using Python', 'https://curriculab-resources.netlify.app/Sem-2/PBA211%20Data%20Analysis%20Using%20Python/PBA211%20Unit-4%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba211', 'unit-4', 'revision_note', 'Unit 4 Revision Notes', 'https://curriculab-resources.netlify.app/Sem-2/PBA211%20Data%20Analysis%20Using%20Python/PBA211%20Unit-4%20Revision%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba211', 'unit-5', 'study_note', 'Unit 5: Data Analysis Using Python', 'https://curriculab-resources.netlify.app/Sem-2/PBA211%20Data%20Analysis%20Using%20Python/PBA211%20Unit-5%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba211', 'unit-5', 'revision_note', 'Unit 5 Revision Notes', 'https://curriculab-resources.netlify.app/Sem-2/PBA211%20Data%20Analysis%20Using%20Python/PBA211%20Unit-5%20Revision%20Notes.html');

INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba212', 'unit-1', 'study_note', 'Unit 1: Data Analysis Using Powerbi', 'https://curriculab-resources.netlify.app/Sem-2/PBA212%20Data%20Analysis%20Using%20Powerbi/PBA212%20Unit-1%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba212', 'unit-1', 'revision_note', 'Unit 1 Revision Notes', 'https://curriculab-resources.netlify.app/Sem-2/PBA212%20Data%20Analysis%20Using%20Powerbi/PBA212%20Unit-1%20Revision%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba212', 'unit-2', 'study_note', 'Unit 2: Data Analysis Using Powerbi', 'https://curriculab-resources.netlify.app/Sem-2/PBA212%20Data%20Analysis%20Using%20Powerbi/PBA212%20Unit-2%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba212', 'unit-2', 'revision_note', 'Unit 2 Revision Notes', 'https://curriculab-resources.netlify.app/Sem-2/PBA212%20Data%20Analysis%20Using%20Powerbi/PBA212%20Unit-2%20Revision%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba212', 'unit-3', 'study_note', 'Unit 3: Data Analysis Using Powerbi', 'https://curriculab-resources.netlify.app/Sem-2/PBA212%20Data%20Analysis%20Using%20Powerbi/PBA212%20Unit-3%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba212', 'unit-3', 'revision_note', 'Unit 3 Revision Notes', 'https://curriculab-resources.netlify.app/Sem-2/PBA212%20Data%20Analysis%20Using%20Powerbi/PBA212%20Unit-3%20Revision%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba212', 'unit-4', 'study_note', 'Unit 4: Data Analysis Using Powerbi', 'https://curriculab-resources.netlify.app/Sem-2/PBA212%20Data%20Analysis%20Using%20Powerbi/PBA212%20Unit-4%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba212', 'unit-4', 'revision_note', 'Unit 4 Revision Notes', 'https://curriculab-resources.netlify.app/Sem-2/PBA212%20Data%20Analysis%20Using%20Powerbi/PBA212%20Unit-4%20Revision%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba212', 'unit-5', 'study_note', 'Unit 5: Data Analysis Using Powerbi', 'https://curriculab-resources.netlify.app/Sem-2/PBA212%20Data%20Analysis%20Using%20Powerbi/PBA212%20Unit-5%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba212', 'unit-5', 'revision_note', 'Unit 5 Revision Notes', 'https://curriculab-resources.netlify.app/Sem-2/PBA212%20Data%20Analysis%20Using%20Powerbi/PBA212%20Unit-5%20Revision%20Notes.html');

INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba213', 'unit-1', 'study_note', 'Unit 1: Business Communication - II', 'https://curriculab-resources.netlify.app/Sem-2/PBA213%20Business%20Communication%20-%20II/PBA213%20Unit-1%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba213', 'unit-1', 'revision_note', 'Unit 1 Revision Notes', 'https://curriculab-resources.netlify.app/Sem-2/PBA213%20Business%20Communication%20-%20II/PBA213%20Unit-1%20Revision%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba213', 'unit-2', 'study_note', 'Unit 2: Business Communication - II', 'https://curriculab-resources.netlify.app/Sem-2/PBA213%20Business%20Communication%20-%20II/PBA213%20Unit-2%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba213', 'unit-2', 'revision_note', 'Unit 2 Revision Notes', 'https://curriculab-resources.netlify.app/Sem-2/PBA213%20Business%20Communication%20-%20II/PBA213%20Unit-2%20Revision%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba213', 'unit-3', 'study_note', 'Unit 3: Business Communication - II', 'https://curriculab-resources.netlify.app/Sem-2/PBA213%20Business%20Communication%20-%20II/PBA213%20Unit-3%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba213', 'unit-3', 'revision_note', 'Unit 3 Revision Notes', 'https://curriculab-resources.netlify.app/Sem-2/PBA213%20Business%20Communication%20-%20II/PBA213%20Unit-3%20Revision%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba213', 'unit-4', 'study_note', 'Unit 4: Business Communication - II', 'https://curriculab-resources.netlify.app/Sem-2/PBA213%20Business%20Communication%20-%20II/PBA213%20Unit-4%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba213', 'unit-4', 'revision_note', 'Unit 4 Revision Notes', 'https://curriculab-resources.netlify.app/Sem-2/PBA213%20Business%20Communication%20-%20II/PBA213%20Unit-4%20Revision%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba213', 'unit-5', 'study_note', 'Unit 5: Business Communication - II', 'https://curriculab-resources.netlify.app/Sem-2/PBA213%20Business%20Communication%20-%20II/PBA213%20Unit-5%20Notes.html');
INSERT INTO vault_resources (subject_id, unit_id, type, title, link) VALUES ('pba213', 'unit-5', 'revision_note', 'Unit 5 Revision Notes', 'https://curriculab-resources.netlify.app/Sem-2/PBA213%20Business%20Communication%20-%20II/PBA213%20Unit-5%20Revision%20Notes.html');

